# Generated by Django 4.2 on 2023-04-03 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('otp_code', models.IntegerField()),
                ('otp_type', models.CharField(choices=[('REGISTER', 'Register')], max_length=20)),
                ('otp_via', models.CharField(choices=[('EMAIL', 'Email')], default='EMAIL', max_length=20)),
                ('trial', models.IntegerField(default=0)),
                ('expired_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
