# Generated by Django 4.2 on 2023-04-04 17:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_uuid', models.UUIDField(blank=True, null=True)),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('otp_code', models.CharField(max_length=6)),
                ('otp_type', models.CharField(choices=[('REGISTER', 'Register')], max_length=20)),
                ('otp_via', models.CharField(choices=[('EMAIL', 'Email')], default='EMAIL', max_length=20)),
                ('otp_status', models.CharField(choices=[('OPEN', 'Open'), ('VERIFIED', 'Verified'), ('EXPIRED', 'Expired'), ('BLOCKED', 'Blocked')], default='OPEN', max_length=20)),
                ('otp_token', models.CharField(max_length=32, unique=True)),
                ('trial', models.IntegerField(default=0)),
                ('expired_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
